### ISSUE TITLE
AWS site blocked

### ISSUE THREAD

**Issue by darrencocco** [TheAntiSocialEngineer/AntiSocial-BlockList-UK-Community#1]
You have listed aws.amazon.com which is where one downloads the AWS CLI tool from etc.

Could you please remove that from the list as it is a legitimate site or provide a justification for its inclusion.

**Comment by p1r473** [comment]
Also please unblock 
`s3-eu-west-amazonaws.com`

**Comment by aglasson** [comment]
I came here for this exactly issue. This blocks even logging into the AWS management console. Something people all around the world do on the daily.

**Comment by rfdevere** [comment]
Thanks for letting us know, added by mistake from manually adding to list.
