### ISSUE TITLE
icloud.com is broken

### ISSUE THREAD

**Issue by iam-py-test** [TheAntiSocialEngineer/AntiSocial-BlockList-UK-Community#2]
`cdn-apple.com` is a safe domain related to icloud; blocking it via `||cdn-apple.com^` breaks Apple's iCloud.
uBlock Origin's logger shows clearly that this list is blocking it.
It works perfectly well when the list is disabled.
See https://www.virustotal.com/gui/url/4d3fc1ad22ce505e90674dfc7820bf83c21298cfdd338b1e624dbdd3b5c7a0e8/detection for more information

**Comment by iam-py-test** [comment]
Is this repo even maintained? 
I opened this 20 days ago, and no-one responded & the last commit was a while ago

**Comment by rfdevere** [comment]
Thank you, removed.
