### ISSUE TITLE
outlookmobile.com should be removed

### ISSUE THREAD

**Issue by grantemsley** [TheAntiSocialEngineer/AntiSocial-BlockList-UK-Community#3]
outlookmobile.com is a legitimate domain owned by Microsoft. The subdomain autodetect.outlookmobile.com is used by Outlook on android for account configuration. Blocking it breaks outlook.

**Comment by iam-py-test** [comment]
> outlookmobile.com is a legitimate domain owned by Microsoft. The subdomain autodetect.outlookmobile.com is used by Outlook on android for account configuration. Blocking it breaks outlook.

@grantemsley it seems that this repo is unmaintained as I opened #2 a while ago (no response) and the last commit was https://github.com/TheAntiSocialEngineer/AntiSocial-BlockList-UK-Community/commit/9cd756bac651f66e5f3c63cf7ceea703db968997 which does not even change the list.
I recommend you disable this list, and maybe it is time someone forks.

**Comment by iam-py-test** [comment]
@grantemsley I have opened a PR (#4) which should fix your issue.
Once @rfdevere has merged it, try updating your lists and see if the problem is resolved

**Comment by iam-py-test** [comment]
@rfdevere please fix this issue

**Comment by rfdevere** [comment]
Thank you, this has been removed.

**Comment by iam-py-test** [comment]
@rfdevere thank you!
