### ISSUE TITLE
False Positive - Facebook.net

### ISSUE THREAD

**Issue by iam-py-test** [TheAntiSocialEngineer/AntiSocial-BlockList-UK-Community#5]
I have noticed that Facebook.net is blocked by this list.
Facebook.net is a website owned by Facebook used for various things - blocking it may cause breakage.
I can fix this in #4, however, @rfdevere will need to merge it.

**Comment by rfdevere** [comment]
Removed, sorry for the delay.

**Comment by iam-py-test** [comment]
@rfdevere thanks!
