### ISSUE TITLE
imsdb.com 

### ISSUE THREAD

**Issue by p1r473** [TheAntiSocialEngineer/AntiSocial-BlockList-UK-Community#7]
This is the The Internet Movie Script Database (IMSDb)
It is not malicious, nor adware. It is a database of movie scripts
I believe this is a false positive.

**Comment by iam-py-test** [comment]
@p1r473 this list appear to be unmaintained 
I recommend you disable it or stop using it

**Comment by p1r473** [comment]
@rfdevere is this list mantained?
Thanks.

**Comment by rfdevere** [comment]
Removed, thank you for the report.

**Comment by rfdevere** [comment]
Removed, thank you for the report.
